import Foundation
import Network

/// Per-connection state for a single (peer, session) pair. Mirrors the
/// shape of `FC-JDK/src/main/java/fudp/connection/PeerConnection.java`
/// but exposes only the fields the Mac client touches today; the loss-
/// detection / sentPackets map is deferred until we wire ack handling
/// into the receive loop in Phase 4.7.
///
/// `connectionId` is the wire-level identifier — 64-bit, randomly
/// generated by whichever side opens the connection. Both sides scope
/// packet-number sequences by this value, so a given peer can have
/// several simultaneous connections (e.g. parallel uploads) without
/// stepping on each other's replay windows.
///
/// `peerPubkey` is the peer's *long-term identity* compressed
/// secp256k1 pubkey — the same byte string they put in their AsyTwoWay
/// bundles. There is no "ephemeral pubkey" in FUDP: identity is the
/// authority, so PeerConnection treats this field as immutable for the
/// connection's lifetime.
public final class PeerConnection: @unchecked Sendable {

    public enum State: String, Sendable, CaseIterable {
        case idle
        case establishing
        case established
        case closing
        case closed
    }

    public enum Failure: Error, CustomStringConvertible {
        case invalidStateTransition(from: State, to: State)
        case invalidPubkeyLength(got: Int)

        public var description: String {
            switch self {
            case let .invalidStateTransition(from, to):
                return "PeerConnection: invalid state transition \(from) → \(to)"
            case let .invalidPubkeyLength(got):
                return "PeerConnection: peer pubkey must be 33 bytes, got \(got)"
            }
        }
    }

    public let connectionId: Int64
    public let peerPubkey: Data
    public let peerAddress: NWEndpoint
    public let peerFid: String?
    public let createdAtMs: Int64

    private let lock = NSLock()

    // Mutable state (all reads/writes under `lock`).
    private var _state: State = .idle
    private var _nextPacketNumberToSend: Int64 = 0
    private var _largestSentPacketNumber: Int64 = -1
    private var _largestAckedPacketNumber: Int64 = -1
    private var _peerSessionEpoch: Int64 = 0
    private var _ourEpochConfirmed: Bool = false
    private var _lastActivityMs: Int64

    public init(
        connectionId: Int64,
        peerPubkey: Data,
        peerAddress: NWEndpoint,
        peerFid: String? = nil,
        nowMs: Int64? = nil
    ) throws {
        guard peerPubkey.count == 33 else {
            throw Failure.invalidPubkeyLength(got: peerPubkey.count)
        }
        self.connectionId = connectionId
        self.peerPubkey = Data(peerPubkey)
        self.peerAddress = peerAddress
        self.peerFid = peerFid
        let now = nowMs ?? PeerConnection.currentTimeMillis()
        self.createdAtMs = now
        self._lastActivityMs = now
    }

    // MARK: - state

    public var state: State {
        lock.lock(); defer { lock.unlock() }
        return _state
    }

    /// Move to a new state. Allowed transitions:
    /// ```
    ///   idle          → establishing / closed
    ///   establishing  → established / closing / closed
    ///   established   → closing / closed
    ///   closing       → closed
    ///   closed        → (none)
    /// ```
    public func transition(to next: State, nowMs: Int64? = nil) throws {
        lock.lock(); defer { lock.unlock() }
        guard PeerConnection.transitionAllowed(from: _state, to: next) else {
            throw Failure.invalidStateTransition(from: _state, to: next)
        }
        _state = next
        _lastActivityMs = nowMs ?? PeerConnection.currentTimeMillis()
    }

    public var isOpen: Bool {
        lock.lock(); defer { lock.unlock() }
        return _state != .closed && _state != .closing
    }

    private static func transitionAllowed(from: State, to: State) -> Bool {
        switch (from, to) {
        case (.idle, .establishing), (.idle, .closed):                   return true
        case (.establishing, .established),
             (.establishing, .closing), (.establishing, .closed):        return true
        case (.established, .closing), (.established, .closed):          return true
        case (.closing, .closed):                                        return true
        default:                                                         return false
        }
    }

    // MARK: - packet numbers

    /// Reserve the next outbound packet number and return it. The
    /// counter starts at 0 and increments by one per call. Callers
    /// should only call this from the send path.
    @discardableResult
    public func nextPacketNumber(nowMs: Int64? = nil) -> Int64 {
        lock.lock(); defer { lock.unlock() }
        let pn = _nextPacketNumberToSend
        _nextPacketNumberToSend += 1
        _largestSentPacketNumber = pn
        _lastActivityMs = nowMs ?? PeerConnection.currentTimeMillis()
        return pn
    }

    public var nextPacketNumberPreview: Int64 {
        lock.lock(); defer { lock.unlock() }
        return _nextPacketNumberToSend
    }

    public var largestSentPacketNumber: Int64 {
        lock.lock(); defer { lock.unlock() }
        return _largestSentPacketNumber
    }

    public func recordPeerAck(largestAcked: Int64, nowMs: Int64? = nil) {
        lock.lock(); defer { lock.unlock() }
        if largestAcked > _largestAckedPacketNumber {
            _largestAckedPacketNumber = largestAcked
        }
        _lastActivityMs = nowMs ?? PeerConnection.currentTimeMillis()
    }

    public var largestAckedPacketNumber: Int64 {
        lock.lock(); defer { lock.unlock() }
        return _largestAckedPacketNumber
    }

    // MARK: - session epoch

    /// Update what we've seen as the peer's session epoch. Returns the
    /// previous value (0 if this is the first epoch we've seen).
    @discardableResult
    public func observePeerEpoch(_ epoch: Int64, nowMs: Int64? = nil) -> Int64 {
        lock.lock(); defer { lock.unlock() }
        let previous = _peerSessionEpoch
        _peerSessionEpoch = epoch
        _lastActivityMs = nowMs ?? PeerConnection.currentTimeMillis()
        return previous
    }

    public var peerSessionEpoch: Int64 {
        lock.lock(); defer { lock.unlock() }
        return _peerSessionEpoch
    }

    /// Until the peer ACKs our epoch we keep including it in every
    /// outbound packet (so they can detect our restart). Once they ack,
    /// we can drop the FLAG_HAS_EPOCH bit and save 8 bytes per packet.
    public var ourEpochConfirmed: Bool {
        lock.lock(); defer { lock.unlock() }
        return _ourEpochConfirmed
    }

    public func markOurEpochConfirmed(nowMs: Int64? = nil) {
        lock.lock(); defer { lock.unlock() }
        _ourEpochConfirmed = true
        _lastActivityMs = nowMs ?? PeerConnection.currentTimeMillis()
    }

    // MARK: - activity

    public var lastActivityMs: Int64 {
        lock.lock(); defer { lock.unlock() }
        return _lastActivityMs
    }

    public func touch(nowMs: Int64? = nil) {
        lock.lock(); defer { lock.unlock() }
        _lastActivityMs = nowMs ?? PeerConnection.currentTimeMillis()
    }

    // MARK: -

    public static func currentTimeMillis() -> Int64 {
        Int64(Date().timeIntervalSince1970 * 1000.0)
    }
}
