import XCTest
@testable import FCDomain
import FCCore

/// The FIMP v2 envelope: the magic prefix, the single body field, the
/// framing inside it, and the size rule that replaced the old constant.
///
/// These do not use the golden vectors. The vectors are v1 and can only
/// be regenerated by the Android client once it encodes v2 (see the
/// skipped parity tests in `ImMessageTests`), so what is asserted here is
/// the format's own internal consistency — which is the part that has to
/// be right *before* the two clients are compared.
final class ImWireV2Tests: XCTestCase {

    private let alice = "FEk41Kqjar45fLDriztUDTUkdki7mmcjWK"
    private let bob = "F6vqNGkbAqZQ1YkPWLcXfNfwvJXCTGmzUM"

    private func text(_ body: String = "hello") -> ImMessage {
        var m = ImMessage.text(type: .p2p, from: alice, to: bob, body)
        m.timestamp = 1_700_000_000_000
        m.id = "0000000000000001"
        return m
    }

    // MARK: - magic and version

    func testEnvelopeOpensWithTheMagicAndVersion() throws {
        let bytes = try text().toWireBytes()
        XCTAssertEqual(bytes.first, 0xF1)
        XCTAssertEqual(bytes.dropFirst().first, 0x02)
    }

    /// The reason the magic exists. A v1 envelope opens with the `ImType`
    /// ordinal, so a bare version byte of 2 would be indistinguishable
    /// from a v1 TEAM message — and a v2 reader would misparse it rather
    /// than reject it. Every v1 first byte must be refused.
    func testV1EnvelopesAreRejectedNotMisparsed() throws {
        for ordinal in UInt8(0) ... UInt8(3) {
            var v1 = try text().toWireBytes()
            v1[v1.startIndex] = ordinal
            XCTAssertThrowsError(try ImMessage.fromWireBytes(v1)) { error in
                guard case ImMessage.WireFailure.notFimp = error else {
                    return XCTFail("ordinal \(ordinal) should be refused as non-v2, got \(error)")
                }
            }
        }
    }

    func testAnUnknownVersionIsRejected() throws {
        var bytes = try text().toWireBytes()
        bytes[bytes.startIndex + 1] = 0x09
        XCTAssertThrowsError(try ImMessage.fromWireBytes(bytes)) { error in
            XCTAssertEqual(error as? ImMessage.WireFailure, .wrongVersion(9))
        }
    }

    // MARK: - body framing

    /// Both payloads travel in one field, and both come back.
    func testContentAndDataRoundTripTogether() throws {
        var m = ImMessage.voice(
            type: .p2p, from: alice, to: bob,
            metaJson: #"{"durationMs":3400}"#, data: Data([0x00, 0x01, 0xFF, 0x7F])
        )
        m.timestamp = 1
        m.id = "0000000000000002"

        let back = try ImMessage.fromWireBytes(try m.toWireBytes())
        XCTAssertEqual(back.content, #"{"durationMs":3400}"#)
        XCTAssertEqual(back.data, Data([0x00, 0x01, 0xFF, 0x7F]))
    }

    /// Binary is binary now. v1 carried it Base64 inside a UTF-8 string
    /// field, which cost a third of the payload and could not express a
    /// byte sequence that was not valid Base64 in the first place.
    func testDataIsCarriedRawNotBase64() throws {
        let payload = Data((0 ..< 256).map { UInt8($0) })
        var m = ImMessage.stream(
            type: .p2p, from: alice, to: bob, metaJson: "{}", data: payload
        )
        m.timestamp = 1
        let encoded = try m.toWireBytes()

        XCTAssertEqual(try ImMessage.fromWireBytes(encoded).data, payload)
        // The raw bytes appear in the envelope; a Base64 rendering would not.
        XCTAssertTrue(encoded.range(of: payload) != nil)
    }

    /// A payload far past v1's 16-bit length prefix, which is the failure
    /// this version exists to end: Android silently wrapped the length and
    /// corrupted every field after it.
    func testAPayloadBeyondSixtyFiveThousandBytesSurvives() throws {
        let payload = Data(repeating: 0x5A, count: 300_000)
        var m = ImMessage.stream(
            type: .p2p, from: alice, to: bob, metaJson: "{}", data: payload
        )
        m.timestamp = 1

        let back = try ImMessage.fromWireBytes(try m.toWireBytes())
        XCTAssertEqual(back.data?.count, 300_000)
        XCTAssertEqual(back.data, payload)
    }

    func testTrailingFieldsSurviveALargeBody() throws {
        var m = ImMessage.stream(
            type: .p2p, from: alice, to: bob, metaJson: "{}",
            data: Data(repeating: 0x11, count: 100_000)
        )
        m.timestamp = 1
        m.id = "00000000deadbeef"
        m.threadId = "thread-9"
        m.replyToId = "00000000cafebabe"

        let back = try ImMessage.fromWireBytes(try m.toWireBytes())
        XCTAssertEqual(back.id, "00000000deadbeef")
        XCTAssertEqual(back.threadId, "thread-9")
        XCTAssertEqual(back.replyToId, "00000000cafebabe")
    }

    // MARK: - sealing is all-or-nothing

    /// The point of the single body field. In v1 this message would have
    /// travelled with its metadata encrypted and its audio in the clear;
    /// here neither payload is visible in the envelope.
    func testSealingCoversTheBinaryPayloadToo() throws {
        let privkey = Data(repeating: 0x11, count: 32)
        let recipientPriv = Data(repeating: 0x22, count: 32)
        let recipientPub = try Secp256k1.publicKey(fromPrivateKey: recipientPriv)

        let audio = Data(repeating: 0xAB, count: 4_000)
        var m = ImMessage.voice(
            type: .p2p, from: alice, to: bob,
            metaJson: #"{"durationMs":3400,"format":"aac"}"#, data: audio
        )
        m.timestamp = 1
        try m.sealBody(privkey: privkey, recipientPubkey: recipientPub)

        XCTAssertNil(m.content, "the metadata is inside the seal")
        XCTAssertNil(m.data, "and so is the audio")
        XCTAssertNotNil(m.body)

        let encoded = try m.toWireBytes()
        XCTAssertNil(encoded.range(of: audio), "no cleartext audio anywhere in the envelope")
        XCTAssertNil(encoded.range(of: Data("durationMs".utf8)), "nor cleartext metadata")

        var received = try ImMessage.fromWireBytes(encoded)
        XCTAssertTrue(received.isSealed)
        XCTAssertTrue(received.openBody(privkey: recipientPriv))
        XCTAssertEqual(received.content, #"{"durationMs":3400,"format":"aac"}"#)
        XCTAssertEqual(received.data, audio)
    }

    /// The sealed flag is what a receiver reads, rather than inferring
    /// from the channel a message arrived on.
    func testSealedFlagTravelsAndAnUnsealedBodyDoesNotSetIt() throws {
        let encodedPlain = try text().toWireBytes()
        XCTAssertEqual(Self.flags(of: encodedPlain) & ImMessage.WireFlag.body, ImMessage.WireFlag.body)
        XCTAssertEqual(Self.flags(of: encodedPlain) & ImMessage.WireFlag.bodySealed, 0)
        XCTAssertFalse(try ImMessage.fromWireBytes(encodedPlain).isSealed)

        var sealed = text()
        try sealed.sealBody(symkey: Data(repeating: 0x33, count: 32), version: 7)
        let encodedSealed = try sealed.toWireBytes()
        XCTAssertEqual(
            Self.flags(of: encodedSealed) & ImMessage.WireFlag.bodySealed,
            ImMessage.WireFlag.bodySealed
        )

        let back = try ImMessage.fromWireBytes(encodedSealed)
        XCTAssertTrue(back.isSealed)
        XCTAssertEqual(back.symkeyVersion, 7)
        XCTAssertNil(back.content)
    }

    func testASealedBodySurvivesTheWireUnchanged() throws {
        let symkey = Data(repeating: 0x44, count: 32)
        var sealed = text("the usual place")
        try sealed.sealBody(symkey: symkey, version: 2)

        var back = try ImMessage.fromWireBytes(try sealed.toWireBytes())
        XCTAssertEqual(back.body, sealed.body, "the bundle is carried byte for byte")
        XCTAssertTrue(back.openBody(symkey: symkey))
        XCTAssertEqual(back.content, "the usual place")
    }

    func testSealingWithNothingToSealThrows() {
        var empty = ImMessage.make(type: .p2p, from: alice, to: bob, contentType: .typing)
        XCTAssertThrowsError(try empty.sealBody(symkey: Data(repeating: 1, count: 32), version: 1))
    }

    /// A message with no payload at all — a typing ping — carries no body
    /// rather than an empty one.
    func testNoPayloadMeansNoBodyField() throws {
        var typing = ImMessage.make(type: .p2p, from: alice, to: bob, contentType: .typing)
        typing.timestamp = 1
        let encoded = try typing.toWireBytes()
        XCTAssertEqual(Self.flags(of: encoded) & ImMessage.WireFlag.body, 0)
        XCTAssertEqual(encoded.count, ImMessage.wireHeaderSize + alice.utf8.count + bob.utf8.count)
    }

    // MARK: - the size rule

    /// The budget is a property of the destination, read from its service
    /// record — not a constant. A record that does not say falls back to
    /// what the server itself defaults to.
    func testItemSizeLimitComesFromTheServiceRecord() {
        XCTAssertEqual(Service(maxDataSize: "262144").itemSizeLimit, 262_144)
        XCTAssertNil(Service(maxDataSize: nil).itemSizeLimit)
        XCTAssertNil(Service(maxDataSize: "").itemSizeLimit)
        XCTAssertNil(Service(maxDataSize: "not a number").itemSizeLimit, "unparseable is 'does not say'")
        XCTAssertNil(Service(maxDataSize: "0").itemSizeLimit, "zero is not a real ceiling")
        XCTAssertNil(Service(maxDataSize: "-1").itemSizeLimit)
    }

    /// The number the previous port asserted in a comment and enforced as
    /// 900 KB. The server's real default is 64 KB.
    func testAssumedLimitMatchesTheServerDefault() {
        XCTAssertEqual(ImMessage.assumedDockItemLimit, 65_536)
    }

    // MARK: - helpers

    /// The flag word sits after magic, version, type, contentType and the
    /// two length-prefixed ids.
    private static func flags(of envelope: Data) -> UInt16 {
        var index = envelope.startIndex + 4
        index += 1 + Int(envelope[index])          // senderId
        index += 1 + Int(envelope[index])          // targetId
        index += 8                                 // timestamp
        return UInt16(envelope[index]) << 8 | UInt16(envelope[index + 1])
    }
}
