import Foundation

/// An enum that the Android side writes **two different ways**, and the
/// difference is the whole reason this protocol exists:
///
/// - in JSON (local storage, and the history file one client shares with
///   another) Gson writes the constant's **name**, which is this type's
///   `rawValue`;
/// - in ``ImMessage/toWireBytes()`` it writes the constant's **ordinal** —
///   its position in the Java declaration order — as a single byte.
///
/// So a constant carries two identities, and only one of them is visible
/// in the source. Reordering a case here (or in Java) leaves every JSON
/// test green while silently re-labelling every message on the wire: a
/// `VOICE` would arrive as a `ROOM_LEAVE`. That is why ``wireOrdinal``
/// reads the declaration order rather than restating it, and why
/// `ImMessageTests` asserts the whole table against numbers generated by
/// the real Java enums.
///
/// `CaseIterable` supplies `allCases` in declaration order; keeping that
/// as the single source means the two identities cannot drift apart
/// within this file.
public protocol JavaOrdinalEnum: RawRepresentable, CaseIterable, Equatable
where RawValue == String, AllCases: RandomAccessCollection, AllCases.Index == Int {}

public extension JavaOrdinalEnum {

    /// The byte the wire format writes for this constant.
    var wireOrdinal: UInt8 {
        UInt8(Self.allCases.firstIndex(of: self) ?? 0)
    }

    /// The constant an ordinal names, or `nil` if this build has never
    /// heard of it.
    ///
    /// Java's `fromWireBytes` guards with `ord < values().length` and
    /// simply leaves the field null when the guard fails, so a message
    /// from a newer client mentioning a content type we don't know yet
    /// still decodes — it just decodes without that field. Returning
    /// `nil` here, rather than throwing, is what reproduces that: an
    /// unknown constant must not take down the whole message.
    init?(wireOrdinal: UInt8) {
        let index = Int(wireOrdinal)
        guard index >= 0, index < Self.allCases.count else { return nil }
        self = Self.allCases[index]
    }

    /// Port of the `fromString` each Java enum carries: case-insensitive,
    /// `nil` rather than an exception when there is no such constant.
    init?(javaName: String?) {
        guard let javaName else { return nil }
        self.init(rawValue: javaName.uppercased())
    }
}

/// The four flavours of conversation.
///
/// Note the second constant: several Java doc comments (and the field
/// comments on `ImMessage` itself) still call it `GROUP`, which it was
/// before squares were named. The constant is `SQUARE`, and since its
/// ordinal is on the wire the name in the comments is the thing that is
/// wrong, not the code.
public enum ImType: String, JavaOrdinalEnum, Codable, Sendable {
    /// Person to person. Sealed with the recipient's pubkey — the
    /// AsyTwoWay envelope from 9.1.1, so the sender can reread their own
    /// messages.
    case p2p = "P2P"
    /// Open group with on-chain membership. No manager, no encryption.
    case square = "SQUARE"
    /// Owner-managed group with on-chain membership, sealed with a team
    /// symkey.
    case team = "TEAM"
    /// Owner-managed group whose membership is defined **locally** —
    /// nothing about a room is on the chain — sealed with a room symkey.
    case room = "ROOM"
}

/// What a message carries. The user-visible kinds are the first three;
/// everything after `HISTORY` is protocol traffic that a chat pane
/// mostly renders as nothing at all.
public enum ContentType: String, JavaOrdinalEnum, Codable, Sendable {
    case text = "TEXT"
    /// A file share: the HAT JSON travels, the bytes do not.
    case hat = "HAT"
    /// Inline binary: metadata in `content`, payload in `dataBase64`.
    case stream = "STREAM"
    case symkey = "SYMKEY"
    case members = "MEMBERS"
    case history = "HISTORY"
    case request = "REQUEST"
    case response = "RESPONSE"
    case typing = "TYPING"
    case receipt = "RECEIPT"
    case presence = "PRESENCE"
    case reaction = "REACTION"
    case edit = "EDIT"
    case delete = "DELETE"
    case forward = "FORWARD"
    case roomInfo = "ROOM_INFO"
    case roomLeave = "ROOM_LEAVE"
    case voice = "VOICE"
    case roomAccept = "ROOM_ACCEPT"
    /// Owner closes the room. A receiver **must** check the sender is the
    /// owner before acting on it.
    case roomDisband = "ROOM_DISBAND"
    /// Owner removes a member. Same owner check applies.
    case roomRemoved = "ROOM_REMOVED"
}

/// What a `REQUEST` is asking for.
public enum RequestType: String, JavaOrdinalEnum, Codable, Sendable {
    case hat = "HAT"
    case members = "MEMBERS"
    case symkey = "SYMKEY"
    case messageSync = "MESSAGE_SYNC"
    case history = "HISTORY"
    case publicKey = "PUBLIC_KEY"
    /// Older symkey versions, so messages from before a rotation stay
    /// readable.
    case symkeyHistory = "SYMKEY_HISTORY"
    case roomInfo = "ROOM_INFO"
}

/// Where a message is in its life. Local-only — this never crosses the
/// wire, which is why a receiver's copy of a message always starts
/// without one.
public enum MessageStatus: String, JavaOrdinalEnum, Codable, Sendable {
    case pending = "PENDING"
    /// Held for the user to look at before it joins the conversation —
    /// the stranger quarantine.
    case quarantined = "QUARANTINED"
    case sent = "SENT"
    case delivered = "DELIVERED"
    case read = "READ"
    case failed = "FAILED"
    /// Came in from a shared history file, so it may be unverified.
    case imported = "IMPORTED"

    /// Reached the network.
    public var isSent: Bool { self == .sent || self == .delivered || self == .read }

    /// Reached the recipient.
    public var isDelivered: Bool { self == .delivered || self == .read }
}

/// How a message got there. Also local-only.
public enum DeliveryMethod: String, JavaOrdinalEnum, Codable, Sendable {
    case fudpDirect = "FUDP_DIRECT"
    case roadRelay = "ROAD_RELAY"
    /// Left with a DOCK server for a recipient who was not online.
    case dockStored = "DOCK_STORED"

    /// Whether the recipient was online when this was delivered. A DOCK
    /// message says nothing about whether they have read it yet.
    public var isOnline: Bool { self == .fudpDirect || self == .roadRelay }
}
