import XCTest
@testable import FCDomain
import FCCore

final class MsgSignatureTests: XCTestCase {

    private let privkey = Data(fcHex: "18e14a7b6a307f426a94f8114701e7c8e774e7f9a47e2c2035db29a206321725")!

    // Generated by freecashj v0.16 `ECKey.signMessage` (see
    // FCCore ToolPrimitivesTests — byte parity is proven there).
    private let javaEcdsaSig = "IMs2aXAV/uP0LV7+r7wGvXvE63FLKDQCTzMR7skCa8V2BylSaQF2ep3l8KUT++OlqOBi3iiPJb5pEiwxEbT0uoY="

    func testEcdsaSignVerifyRoundTrip() throws {
        let signature = try MsgSignature.sign(message: "hello freer", privkey: privkey, alg: .ecdsa)
        XCTAssertEqual(signature.sign, javaEcdsaSig)
        XCTAssertNotNil(signature.fid)
        XCTAssertTrue(signature.verify())

        var tampered = signature
        tampered.msg = "hello freer!"
        XCTAssertFalse(tampered.verify())
    }

    func testSchnorrSignVerifyRoundTrip() throws {
        let signature = try MsgSignature.sign(message: "schnorr 消息", privkey: privkey, alg: .schnorr)
        XCTAssertTrue(signature.verify())

        // sign = base64(pubkey33 ‖ sig64)
        let bundle = Data(base64Encoded: signature.sign)
        XCTAssertEqual(bundle?.count, 33 + 64)

        var wrongFid = signature
        wrongFid.fid = "FEk41Kqjar45fLDriztUDTUkdki7mmcjWK"
        XCTAssertFalse(wrongFid.verify())
    }

    func testSymkeySignVerify() {
        let key = Data(fcHex: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")!
        let signature = MsgSignature.sign(message: "sym message", symkey: key)
        XCTAssertEqual(signature.keyName, Hash.sha256(key).prefix(6).fcToolHex)
        XCTAssertTrue(signature.verify(symkey: key))
        XCTAssertFalse(signature.verify(symkey: Data(repeating: 9, count: 32)))
        // Asymmetric verify path refuses symkey signatures.
        XCTAssertFalse(signature.verify())
    }

    func testSymkeyVerifyAcceptsLegacyForm() {
        let key = Data(repeating: 7, count: 32)
        let msg = "legacy form"
        let legacySign = Hash.doubleSha256(Data(msg.utf8) + key).fcToolHex
        let signature = MsgSignature(fid: nil, keyName: nil, msg: msg, sign: legacySign, alg: .symkey)
        XCTAssertTrue(signature.verify(symkey: key))
    }

    func testJsonRoundTripAndFieldOrder() throws {
        let signature = try MsgSignature.sign(message: "json \"quoted\" msg", privkey: privkey, alg: .ecdsa)
        let json = signature.toJson()
        // Java ShortSign order: fid, msg, sign, alg (keyName only for symkey).
        XCTAssertTrue(json.range(of: #""fid":.*"msg":.*"sign":.*"alg":"#, options: .regularExpression) != nil)
        let parsed = try MsgSignature.fromJson(json)
        XCTAssertEqual(parsed, signature)
        XCTAssertTrue(parsed.verify())
    }

    func testFromJsonAcceptsJavaLongAliases() throws {
        let json = """
        {"address":"FEk41Kqjar45fLDriztUDTUkdki7mmcjWK","message":"m","signature":"c2ln","algorithm":"BTC-EcdsaSignMsg@No1_NrC7"}
        """
        let parsed = try MsgSignature.fromJson(json)
        XCTAssertEqual(parsed.fid, "FEk41Kqjar45fLDriztUDTUkdki7mmcjWK")
        XCTAssertEqual(parsed.msg, "m")
        XCTAssertEqual(parsed.sign, "c2ln")
        XCTAssertEqual(parsed.alg, .ecdsa)
    }

    func testFromJsonDefaultsMissingAlgToEcdsa() throws {
        let parsed = try MsgSignature.fromJson(#"{"fid":"F","msg":"m","sign":"s"}"#)
        XCTAssertEqual(parsed.alg, .ecdsa)
    }

    func testFromJsonRejectsGarbage() {
        XCTAssertThrowsError(try MsgSignature.fromJson("not json"))
        XCTAssertThrowsError(try MsgSignature.fromJson(#"{"fid":"F"}"#))
    }
}
