import XCTest
@testable import FCCore

final class PhraseKeyTests: XCTestCase {

    func testLegacySha256MatchesVectors() throws {
        let vectors = try TestVectors.load()
        XCTAssertFalse(vectors.phraseToPrivkey.isEmpty)
        for vector in vectors.phraseToPrivkey {
            let priv = try PhraseKey.privateKey(
                fromPhrase: vector.phraseUtf8, scheme: .legacySha256
            )
            XCTAssertEqual(priv.hex, vector.legacy.privkeyHex,
                           "legacy privkey '\(vector.phraseUtf8)'")

            // Cross-check: the derived privkey must produce the same
            // pubkey freecashj produced — ties the whole chain together.
            let pub = try Secp256k1.publicKey(fromPrivateKey: priv)
            XCTAssertEqual(pub.hex, vector.legacy.pubkeyHex,
                           "legacy pubkey '\(vector.phraseUtf8)'")
        }
    }

    /// testVectors.json's `argon2id` block was generated by tools/vector-gen with
    /// the pre-FTSP28 FreerForMac salt, so it pins the recovery scheme. The
    /// conformant scheme is checked against the shared FTSP vectors below.
    func testLegacyFreerMacArgon2idMatchesVectors() throws {
        let vectors = try TestVectors.load()
        for vector in vectors.phraseToPrivkey {
            let priv = try PhraseKey.privateKey(
                fromPhrase: vector.phraseUtf8, scheme: .legacyFreerMacArgon2id
            )
            XCTAssertEqual(priv.hex, vector.argon2id.privkeyHex,
                           "argon2id privkey '\(vector.phraseUtf8)'")

            let pub = try Secp256k1.publicKey(fromPrivateKey: priv)
            XCTAssertEqual(pub.hex, vector.argon2id.pubkeyHex,
                           "argon2id pubkey '\(vector.phraseUtf8)'")
        }
    }

    /// The two schemes must produce different keys for the same phrase —
    /// otherwise upgrading users would be silently broken.
    func testSchemesProduceDifferentKeysForSamePhrase() throws {
        let phrase = "correct horse battery staple"
        let legacy = try PhraseKey.privateKey(fromPhrase: phrase, scheme: .legacySha256)
        let argon = try PhraseKey.privateKey(fromPhrase: phrase, scheme: .argon2id)
        let oldMac = try PhraseKey.privateKey(fromPhrase: phrase, scheme: .legacyFreerMacArgon2id)
        XCTAssertNotEqual(legacy, argon)
        XCTAssertNotEqual(oldMac, argon)
    }

    func testRejectsEmptyPhrase() {
        for scheme in PhraseKey.Scheme.allCases {
            XCTAssertThrowsError(
                try PhraseKey.privateKey(fromPhrase: "", scheme: scheme)
            ) { error in
                guard case PhraseKey.Failure.emptyPhrase = error else {
                    XCTFail("expected emptyPhrase, got \(error)"); return
                }
            }
        }
    }

    /// The safety metadata must clearly mark legacy as not-recommended
    /// and must carry a non-nil advisory string. UI layers rely on this.
    func testLegacySchemeIsMarkedUnsafe() {
        XCTAssertFalse(PhraseKey.Scheme.legacySha256.isRecommendedForNewKeys)
        XCTAssertNotNil(PhraseKey.Scheme.legacySha256.advisory)

        XCTAssertFalse(PhraseKey.Scheme.legacyFreerMacArgon2id.isRecommendedForNewKeys)
        XCTAssertNotNil(PhraseKey.Scheme.legacyFreerMacArgon2id.advisory)

        XCTAssertTrue(PhraseKey.Scheme.argon2id.isRecommendedForNewKeys)
        XCTAssertNil(PhraseKey.Scheme.argon2id.advisory)
    }

    /// FTSP28 pins the conformant salt empty; the recovery scheme keeps the old one.
    func testSalts() {
        XCTAssertTrue(PhraseKey.argon2idSalt.isEmpty)
        XCTAssertEqual(String(data: PhraseKey.legacyFreerMacSalt, encoding: .utf8), "fc.freer.phrase.v1")
    }

    /// The shared FTSP28 vectors: a phrase must give the same key here as in
    /// FC-JDK, Safe and Freer Android. Copied in by Freeverse/tools/sync-ftsp-vectors.sh.
    func testFtspPhraseVectors() throws {
        guard let url = Bundle.module.url(forResource: "phrase", withExtension: "json", subdirectory: "ftsp-vectors") else {
            return XCTFail("ftsp-vectors/phrase.json missing; run Freeverse/tools/sync-ftsp-vectors.sh")
        }
        let root = try JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any]
        let vectors = try XCTUnwrap(root?["vectors"] as? [[String: Any]])
        XCTAssertFalse(vectors.isEmpty)
        for v in vectors {
            let id = v["id"] as? String ?? "?"
            let phrase = try XCTUnwrap(v["phrase"] as? String, id)
            XCTAssertEqual(Data(phrase.utf8).hex, v["phraseUtf8Hex"] as? String, id)
            let scheme: PhraseKey.Scheme
            switch v["scheme"] as? String {
            case "argon2id-empty-salt": scheme = .argon2id
            case "argon2id-freerformac-salt": scheme = .legacyFreerMacArgon2id
            case "sha256": scheme = .legacySha256
            case "argon2id-sha256prefix16-salt":
                // Old Freer Android builds only; FreerForMac never offered it, so check the primitive.
                let salt = Data(Hash.sha256(Data(phrase.utf8)).prefix(16))
                XCTAssertEqual(try Argon2.hashID(password: Data(phrase.utf8), salt: salt).hex, v["priKey32"] as? String, id)
                continue
            default:
                XCTFail("unknown scheme in \(id)")
                continue
            }
            XCTAssertEqual(try PhraseKey.privateKey(fromPhrase: phrase, scheme: scheme).hex, v["priKey32"] as? String, id)
        }
    }
}
