import Foundation
import XCTest

/// Loader for the golden test vectors produced by `tools/vector-gen/`.
///
/// The JSON is committed at `Tests/FCCoreTests/Resources/testVectors.json`
/// and regenerated by the Java generator (freecashj + BouncyCastle) when
/// primitives are added or parameters change.
enum TestVectors {

    struct Root: Decodable {
        let generatedAt: String
        let schemaVersion: Int
        let generator: String
        let sampleKey: SampleKey
        let argon2id: [Argon2Case]
        let sha256: [ShaCase]
        let ripemd160: [SimpleHashCase]
        let hash160: [SimpleHashCase]
        let aesGcm256: [AeadCase]
        let chacha20Poly1305: [AeadCase]
        let hkdfSha256: [HkdfCase]
        let hkdfSha512: [HkdfCase]
        let ecdsa: [EcdsaCase]
        let ecdh: [EcdhCase]

        enum CodingKeys: String, CodingKey {
            case generatedAt = "generated_at"
            case schemaVersion = "schema_version"
            case generator
            case sampleKey = "sample_key"
            case argon2id
            case sha256
            case ripemd160
            case hash160
            case aesGcm256 = "aes_gcm_256"
            case chacha20Poly1305 = "chacha20_poly1305"
            case hkdfSha256 = "hkdf_sha256"
            case hkdfSha512 = "hkdf_sha512"
            case ecdsa
            case ecdh
        }
    }

    struct EcdsaCase: Decodable {
        let label: String
        let messageHex: String
        let messageHashHex: String
        let signatureDerHex: String
        let signatureCompactHex: String

        enum CodingKeys: String, CodingKey {
            case label
            case messageHex = "message_hex"
            case messageHashHex = "message_hash_hex"
            case signatureDerHex = "signature_der_hex"
            case signatureCompactHex = "signature_compact_hex"
        }
    }

    struct EcdhCase: Decodable {
        let label: String
        let alicePrivkeyHex: String
        let alicePubkeyHex: String
        let bobPrivkeyHex: String
        let bobPubkeyHex: String
        let sharedXHex: String

        enum CodingKeys: String, CodingKey {
            case label
            case alicePrivkeyHex = "alice_privkey_hex"
            case alicePubkeyHex = "alice_pubkey_hex"
            case bobPrivkeyHex = "bob_privkey_hex"
            case bobPubkeyHex = "bob_pubkey_hex"
            case sharedXHex = "shared_x_hex"
        }
    }

    struct AeadCase: Decodable {
        let label: String
        let keyHex: String
        let ivHex: String
        let plaintextHex: String
        let aadHex: String
        let ciphertextHex: String
        let tagHex: String

        enum CodingKeys: String, CodingKey {
            case label
            case keyHex = "key_hex"
            case ivHex = "iv_hex"
            case plaintextHex = "plaintext_hex"
            case aadHex = "aad_hex"
            case ciphertextHex = "ciphertext_hex"
            case tagHex = "tag_hex"
        }
    }

    struct HkdfCase: Decodable {
        let label: String
        let ikmHex: String
        let saltHex: String
        let infoHex: String
        let outputLength: Int
        let outputHex: String

        enum CodingKeys: String, CodingKey {
            case label
            case ikmHex = "ikm_hex"
            case saltHex = "salt_hex"
            case infoHex = "info_hex"
            case outputLength = "output_length"
            case outputHex = "output_hex"
        }
    }

    struct SampleKey: Decodable {
        let privkeyHex: String
        let privkeyWif: String
        let pubkeyHex: String
        let fid: String
        let pubkeyHash160Hex: String

        enum CodingKeys: String, CodingKey {
            case privkeyHex = "privkey_hex"
            case privkeyWif = "privkey_wif"
            case pubkeyHex = "pubkey_hex"
            case fid
            case pubkeyHash160Hex = "pubkey_hash160_hex"
        }
    }

    struct Argon2Case: Decodable {
        let label: String
        let passwordHex: String
        let saltHex: String
        let iterations: UInt32
        let memoryKib: UInt32
        let parallelism: UInt32
        let outputLength: Int
        let outputHex: String

        enum CodingKeys: String, CodingKey {
            case label
            case passwordHex = "password_hex"
            case saltHex = "salt_hex"
            case iterations
            case memoryKib = "memory_kib"
            case parallelism
            case outputLength = "output_length"
            case outputHex = "output_hex"
        }
    }

    struct ShaCase: Decodable {
        let label: String
        let inputHex: String
        let sha256Hex: String
        let doubleSha256Hex: String

        enum CodingKeys: String, CodingKey {
            case label
            case inputHex = "input_hex"
            case sha256Hex = "sha256_hex"
            case doubleSha256Hex = "double_sha256_hex"
        }
    }

    struct SimpleHashCase: Decodable {
        let label: String
        let inputHex: String
        let outputHex: String

        enum CodingKeys: String, CodingKey {
            case label
            case inputHex = "input_hex"
            case outputHex = "output_hex"
        }
    }

    static func load(file: StaticString = #file, line: UInt = #line) throws -> Root {
        guard let url = Bundle.module.url(forResource: "testVectors", withExtension: "json") else {
            XCTFail("testVectors.json missing from test bundle; run tools/vector-gen/gradlew run", file: file, line: line)
            throw CocoaError(.fileReadNoSuchFile)
        }
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Root.self, from: data)
    }
}

// MARK: - hex helpers

extension Data {
    /// Parses an ASCII hex string. Aborts on malformed input — the test bundle is trusted.
    init(fromHex hex: String) {
        precondition(hex.count % 2 == 0, "hex string has odd length: \(hex)")
        var data = Data(capacity: hex.count / 2)
        var idx = hex.startIndex
        while idx < hex.endIndex {
            let next = hex.index(idx, offsetBy: 2)
            guard let byte = UInt8(hex[idx..<next], radix: 16) else {
                preconditionFailure("invalid hex byte: \(hex[idx..<next])")
            }
            data.append(byte)
            idx = next
        }
        self = data
    }

    var hex: String {
        map { String(format: "%02x", $0) }.joined()
    }
}
